### ISSUE TITLE
clean the workspace configuration file

### ISSUE THREAD

**Issue by ohmybosh** [yunyanliluo/Authen#1]
Hi yunyanliluo, 

Thanks for your great efforts! I enjoy your work much, but can you help clean the workspace-related repo files a bit? I found it contains `.DS_Store`, `.idea/`, etc. I am considering fork your repo and I am hoping to use my own workplace configures without corrupting the git trackings.

I appreciate your work 👍

**Comment by yunyanliluo** [comment]
Hi Bob, 

Thank you for your kind suggestions. I will update my configuration files at once. Sorry for the inconvenience made to you. I will attempt to watch your progress and focus on coming up with suggestions for you in compensation! Hope I can help with your improvement. 

I appreciate your appreciation very much. I will go further with your help.

**Comment by yunyanliluo** [comment]
By the way, if you are in a hurry to go ahead with my original codes it's good for you to fork and delete configuration files on your own. Hope you a good experience!
